Link google colab : https://colab.research.google.com/drive/1niSsN64Wn_um83VGtXwNedCqWccplcS5?usp=sharing

## ĐẠI HỌC KHOA HỌC TỰ NHIÊN - ĐHQG HCM

## KHOA CÔNG NGHỆ THÔNG TIN 

### MÔN HỌC: TRỰC QUAN HÓA DỮ LIỆU

### ĐỒ ÁN MÔN HỌC HỌC KÌ II – NĂM HỌC 2021-2022

### Thành viên nhóm:

`1. 19120330 - Nguyễn Đoan Phúc`

`2. 19120606 - Nguyễn Đình Hoàng Nguyên`

`3. 19120643 - Đào Thị Thiện Tâm`

`4. 19120683 - Thái Trung Tín`

`5. 19120715 - Nguyễn Kha Vĩ`

#I. Import thư viện

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive

import seaborn as sns
import matplotlib.pylab as plt

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# II. Đọc dữ liệu

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Nhom14_19120330_19120606_19120643_19120683_19120715/Data_Visualization/cleaned.csv')
df = df.iloc[:, 2:]
df.head(5)

,Dia,GDCD,Hoa,Li,Ma_mon_ngoai_ngu,Ngoai_ngu,Sinh,Su,Toan,Van,sbd,Cum_thi
0,7.00,6.50,NaN,NaN,N1,4.2,NaN,4.75,6.4,6.75,18014547,Bắc Giang
1,7.75,7.75,NaN,NaN,N1,2.8,NaN,3.75,7.6,6.00,18014530,Bắc Giang
2,6.50,NaN,NaN,NaN,NaN,NaN,NaN,4.00,4.8,4.75,18014521,Bắc Giang
3,8.00,9.50,NaN,NaN,N1,5.8,NaN,8.25,8.0,7.00,18014517,Bắc Giang
4,NaN,NaN,8.5,8.0,N1,4.0,5.0,NaN,8.2,6.50,18014523,Bắc Giang

# III. Trực quan hóa dữ liệu

###1. Mối quan hệ tương quan giữa điểm thi các môn học

In [ ]:
subjects=['Dia','GDCD','Hoa','Li','Ngoai_ngu','Sinh', 'Su',	'Toan',	'Van']
subjects_df=pd.DataFrame(df[subjects].corr(method ='pearson'),index=subjects,columns=subjects)
df[subjects].corr()

In [ ]:
subjects=['Dia','GDCD','Hoa','Li','Ngoai_ngu','Sinh', 'Su',	'Toan',	'Van']
subjects_df=pd.DataFrame(df[subjects].corr(),index=subjects,columns=subjects)
plt.figure(figsize=subjects_df.shape)
sns.heatmap(subjects_df,vmin=-1, vmax=1, annot=True)

### 2. Môn ngoại ngữ nào (ngoại trừ Tiếng Anh) có nhiều thí sinh tham gia nhất? Môn ngoại ngữ nào có điểm thi trung bình cao nhất?

In [ ]:
foreign_language=df[['Ma_mon_ngoai_ngu','Ngoai_ngu']][df['Ma_mon_ngoai_ngu']!='N1']

foreign_language=foreign_language.dropna()


fig = plt.figure(figsize =(10, 7))
plt.bar(['Tiếng Trung','Tiếng Nhật', 'Tiếng Pháp', 'Tiếng Nga', 'Tiếng Đức'], foreign_language['Ma_mon_ngoai_ngu'].value_counts(), color ='maroon')
 # x-axis : foreign_language['Ma_mon_ngoai_ngu'].value_counts().index
plt.xlabel("Mã môn ngoại ngữ")
plt.ylabel("Số thí sinh tham gia ")
plt.title("Số thí sinh dự thi các môn ngoại ngữ",fontweight ='bold')
plt.show()

In [ ]:
avarage_score=foreign_language['Ma_mon_ngoai_ngu'].value_counts().reset_index(name='count')
avarage_score['subject']=['Tiếng Trung','Tiếng Nhật', 'Tiếng Pháp', 'Tiếng Nga', 'Tiếng Đức']
avarage_score['mean']=np.nan
avarage_score
for i in range(len(avarage_score['subject'].unique())):
         avarage_score.loc[i,'mean']=np.mean(foreign_language[foreign_language['Ma_mon_ngoai_ngu']==avarage_score.loc[i,'index']]['Ngoai_ngu'])
avarage_score=avarage_score.sort_values ('mean', ascending=False)
fig = plt.figure(figsize =(10, 7))
plt.bar(avarage_score['subject'].tolist(), avarage_score['mean'].tolist())

plt.xlabel("Mã môn ngoại ngữ")
plt.ylabel("Điểm trung bình")
plt.title("Số thí sinh dự thi các môn ngoại ngữ",fontweight ='bold')
plt.show()

### 3. Tỉ lệ số lượng điểm 10 ở tất cả các tỉnh thành với cả nước và 10 tỉnh thành có số lượng điểm 10 cao nhất.

In [ ]:
df_10_points = df[(df["Toan"] == 10) | (df["Van"] == 10) | (df["Ngoai_ngu"] == 10)
             | (df["Li"] == 10) | (df["Hoa"] == 10) | (df["Sinh"] == 10)
             | (df["Su"] == 10) | (df["Dia"] == 10) | (df["GDCD"] == 10)].groupby(['Cum_thi']).size().reset_index(name='10_point')
df_10_points = df_10_points.sort_values(by=['10_point'], ascending=False)
fig = plt.figure(figsize=(20,15))
plt.pie(df_10_points.loc[: ,"10_point"], labels = df_10_points.loc[:, 'Cum_thi'], autopct="%1.2f%%")
plt.show();

In [ ]:
plt.figure(figsize=(12,8))
plt.bar(df_10_points.head(10)["Cum_thi"], df_10_points.head(10)["10_point"], align='center');

### 4. So sánh điểm trung bình tất cả các môn giữa TP. Hồ Chí Minh, TP. Hà Nội và cả nước

In [ ]:
df_HCM = df.loc[df["Cum_thi"] == "TP. Hồ Chí Minh"]
df_HN = df.loc[df["Cum_thi"] == "Hà Nội"]
columns = ["Dia", "GDCD", "Su", "Hoa", "Li", "Sinh", "Ngoai_ngu", "Toan", "Van"]

label_loc = np.linspace(start=0, stop=2 * np.pi, num=len(df[columns].mean()))

plt.figure(figsize=(10, 10))
plt.subplot(polar=True)
plt.plot(label_loc, df[columns].mean(), label='Cả nước')
plt.plot(label_loc, df_HCM[columns].mean(), label='TP. Hồ Chí Minh')
plt.plot(label_loc, df_HN[columns].mean(), label='Hà Nội')

lines, labels = plt.thetagrids(np.degrees(label_loc), labels=columns)
plt.legend()
plt.show()

### 5. Sự phân bố và phân tán dữ liệu của các môn tự nhiên

In [ ]:
fig,axs=plt.subplots(2,2,figsize=(10,7))
khoi_tu_nhien = ['Toan', 'Li', 'Hoa', 'Sinh']
pos=[(0,0),(0,1),(1,0),(1,1)]
j=0
for i in khoi_tu_nhien:
    sns.boxplot(ax=axs[pos[j]],x=df[i])
    fig.show()
    j=j+1

# IV. Phân tích dữ liệu

### 1. Thống kê mô tả

In [ ]:
df.describe()

### 2. Phân tích hồi quy

In [ ]:
import statsmodels.api as sm
from statsmodels.api import Logit

In [ ]:
columns_Khoi_A = ["Toan", "Li", "Hoa"]
df_Khoi_A = df[columns_Khoi_A].dropna()
df_Khoi_A["Tong_diem"] = df_Khoi_A["Toan"] + df_Khoi_A["Li"] + df_Khoi_A["Hoa"]
df_Khoi_A["Ket_qua"] = np.where(df_Khoi_A["Tong_diem"] >= 27.2, 1, 0)
df_Khoi_A.head(5)

In [ ]:
x_Khoi_A = df_Khoi_A["Toan"]
y_Khoi_A =df_Khoi_A["Ket_qua"]
MLE_Khoi_A = Logit(y_Khoi_A, sm.add_constant(x_Khoi_A)).fit()
MLE_Khoi_A.summary()

In [ ]:
g = 1 / (1 + np.exp(48.1823 - 4.8775 * df_Khoi_A["Toan"].sort_values()))
plt.plot(df_Khoi_A["Toan"].sort_values(), g)
plt.xlabel("Điểm Toán")
plt.ylabel("Tỉ lệ đậu")
plt.title("Tỉ lệ đậu dựa vào điểm Toán xét theo khối A00")
plt.show()

In [ ]:
columns_Khoi_A1 = ["Toan", "Li", "Ngoai_ngu", "Ma_mon_ngoai_ngu"]
df_Khoi_A1 = df[columns_Khoi_A1].dropna()
df_Khoi_A1 = df_Khoi_A1.loc[df_Khoi_A1["Ma_mon_ngoai_ngu"] == "N1"]
df_Khoi_A1["Tong_diem"] = df_Khoi_A1["Toan"] + df_Khoi_A1["Li"] + df_Khoi_A1["Ngoai_ngu"]
df_Khoi_A1["Ket_qua"] = np.where(df_Khoi_A1["Tong_diem"] >= 27.2, 1, 0)
df_Khoi_A1.head(5)

In [ ]:
x_Khoi_A1 = df_Khoi_A1["Toan"]
y_Khoi_A1 = df_Khoi_A1["Ket_qua"]
MLE_Khoi_A1 = Logit(y_Khoi_A1, sm.add_constant(x_Khoi_A1)).fit()
MLE_Khoi_A1.summary()

In [ ]:
g = 1 / (1 + np.exp(44.0927 - 4.3339 * df_Khoi_A1["Toan"].sort_values()))
plt.plot(df_Khoi_A1["Toan"].sort_values(), g)
plt.xlabel("Điểm Toán")
plt.ylabel("Tỉ lệ đậu")
plt.title("Tỉ lệ đậu dựa vào điểm Toán xét theo khối A01")
plt.show()